<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ZMatrixConfig</RootNamespace>
    <AssemblyName>Config</AssemblyName>
  </PropertyGroup>
</Project>
